### ISSUE TITLE
Control; 'name_unique' option

### ISSUE THREAD

**Issue by BrodyB** [snowkit/mint#16]
Currently, if a Mint control is added into a Luxe scene with a duplicate name, the scene will throw a warning.

It'd be great if Mint control options had the 'name_unique' parameter like Luxe objects have, so this is handled in the constructor.

**Comment by underscorediscovery** [comment]
Upon further thought, it seems more sensible to default to a good name + unique id and the explicit name override to be what it's intended: explicit.

What that means is previously, the defaults were sensible plain names:
- `button`
- `progress` 

Now:
- `button.2F6xWQ`
- `progress.8FCHj`

This means that you can create controls freely without naming overlaps, since the name is not a function of the library usage, unless explicitly required to be, in which case the application implementation detail will handle both of those. The library provides the option to be explicit.
